%chk=co
#P HF/6-311G
# Opt( MaxCycle=10) 
# Gfinput IOP(6/7=3)  Pop=full  Density  Test 
# Units(Ang,Deg)

Input file generated by gabedit...

0 	1 	
C	0	-3.7014990000	0.5140970000	-11.9064880000
O	0	0.3701500000	0.4729690000	-11.7400970000





